### ISSUE TITLE
Support for "close when overlay clicked"

### ISSUE THREAD

**Issue by moroshko** [vegetableman/react-modal-component#2]
I really like the animation support in this library.

Are there any plans to add config options for:
- close modal when overlay clicked
- close modal when ESC clicked

?

**Comment by vegetableman** [comment]
The animation api support was the main driver behind building this repo, as I couldn't find any other. Yep, will add those config options. Btw, PR's are welcome as well ;).

**Comment by moroshko** [comment]
[react-portal](https://github.com/tajo/react-portal) has these 2 config options, so if your lib had them too I'd prefer to use yours over react-portal. Thanks for your support.

**Comment by vegetableman** [comment]
Added support. Checkout example.

**Comment by moroshko** [comment]
@vegetableman Great, thanks a lot!
